routes/web.php
<?php

use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PdfGenerator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\NurseController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\RoleController;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'verified']], function () {

    Route::get('/index', [DashboardController::class, 'index'])->name('index');
    Route::get('/exportCsv',[DashboardController::class,'exportCsv'])->name('exportCsv');

    Route::group(['prefix' => 'doctor', 'as' => 'doctor.'], function () {
        Route::get('/', [DoctorController::class, 'index'])->name('index');
        Route::get('/create', [DoctorController::class, 'create'])->name('create');
        Route::post('/store', [DoctorController::class, 'store'])->name('store');
        Route::get('/datatable', [DoctorController::class, 'datatable'])->name('datatable');
        Route::get('/edit/{id}', [DoctorController::class, 'edit'])->name('edit');
        Route::post('/update', [DoctorController::class, 'update'])->name('update');
        Route::post('/delete', [DoctorController::class, 'delete'])->name('delete');
        Route::get('/viewAppointment',[DoctorController::class,'viewAppointment'])->name('viewAppointment');

        //---Doctor Patient Routes---//
        Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
            Route::get('/', [DoctorController::class, 'indexDoctorPatient'])->name('index');
            Route::get('/select', [DoctorController::class, 'select'])->name('select');
            Route::get('/add/{id}', [DoctorController::class, 'addPatient'])->name('addPatient');
            Route::get('/patientdatatable', [DoctorController::class, 'patientdatatable'])->name('patientdatatable');
            Route::post('/store', [DoctorController::class, 'storePatient'])->name('storePatient');
            Route::post('/delete', [DoctorController::class, 'deletePatient'])->name('deletePatient');

        });
    });

    //--Nurses Route--//
    Route::group(['prefix' => 'nurse', 'as' => 'nurse.'], function () {
        Route::get('/', [NurseController::class, 'index'])->name('index');
        Route::get('/create', [NurseController::class, 'create'])->name('create');
        Route::post('/store', [NurseController::class, 'store'])->name('store');
        Route::get('/datatable', [NurseController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [NurseController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [NurseController::class, 'edit'])->name('edit');
        Route::post('/update', [NurseController::class, 'update'])->name('update');
        Route::get('/selectDepartment', [NurseController::class, 'selectDepartment'])->name('selectDepartment');
    });

    //--Staff Route--//
    Route::group(['prefix' => 'staff', 'as' => 'staff.'], function () {
        Route::get('/', [StaffController::class, 'index'])->name('index');
        Route::get('/create', [StaffController::class, 'create'])->name('create');
        Route::post('/store', [StaffController::class, 'store'])->name('store');
        Route::get('/datatable', [StaffController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [StaffController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [StaffController::class, 'edit'])->name('edit');
        Route::post('/update', [StaffController::class, 'update'])->name('update');
    });

    //--Department--//
    Route::group(['prefix' => 'department', 'as' => 'department.'], function () {
        Route::get('/', [DepartmentController::class, 'index'])->name('index');
        Route::get('/create', [DepartmentController::class, 'create'])->name('create');
        Route::post('/store', [DepartmentController::class, 'store'])->name('store');
        Route::get('/datatable', [DepartmentController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [DepartmentController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [DepartmentController::class, 'edit'])->name('edit');
        Route::post('/update', [DepartmentController::class, 'update'])->name('update');
    });

    //--Patient--//
    Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
        Route::get('/', [PatientController::class, 'index'])->name('index');
        Route::get('/create', [PatientController::class, 'create'])->name('create');
        Route::post('/store', [PatientController::class, 'store'])->name('store');
        Route::get('/datatable', [PatientController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [PatientController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [PatientController::class, 'edit'])->name('edit');
        Route::post('/update', [PatientController::class, 'update'])->name('update');
        Route::get('/viewAppointment',[PatientController::class,'viewAppointment'])->name('viewAppointment');
    });

    //---User Routes---//
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/add',[UserController::class,'add'])->name('add');
        Route::get('/view',[UserController::class,'view'])->name('view');
        Route::post('/create',[UserController::class,'create'])->name('create');
        Route::get('/edit/{id}', [UserController::class, 'index'])->name('edit');
        Route::post('/update', [UserController::class, 'update'])->name('update');
        Route::get('/datatable',[UserController::class,'usersList'])->name('datatable');
        Route::post('/delete',[UserController::class,'delete'])->name('delete');
    });

//---Room Routes---//
    Route::group(['prefix' => 'room', 'as' => 'room.'], function () {
        Route::get('/', [RoomController::class, 'index'])->name('index');
        Route::get('/create', [RoomController::class, 'create'])->name('create');
        Route::post('/store', [RoomController::class, 'store'])->name('store');
        Route::get('/datatable',[RoomController::class,'datatable'])->name('datatable');
        Route::post('/delete',[RoomController::class,'delete'])->name('delete');
        Route::get('/edit/{id}',[RoomController::class,'edit'])->name('edit');
        Route::post('update',[RoomController::class,'update'])->name('update');

        Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
            Route::get('/', [RoomController::class, 'indexpatient'])->name('index');
            Route::get('/create',[RoomController::class,'createPatient'])->name('create');
            Route::post('/store',[RoomController::class,'storePatient'])->name('store');
            Route::get('/select',[RoomController::class,'select'])->name('select');
            Route::get('/patientDatatable',[RoomController::class,'patientDatatable'])->name('patientDatatable');
            Route::post('/delete',[RoomController::class,'deletePatient'])->name('delete');
        });

    });

    //---Appointment Routes---//
    Route::group(['prefix' => 'appointment', 'as' => 'appointment.'], function () {
        Route::get('/', [AppointmentController::class, 'index'])->name('index');
        Route::get('/create',[AppointmentController::class,'create'])->name('create');
        Route::get('/datatable',[AppointmentController::class,'datatable'])->name('datatable');
        Route::get('/selectPatient',[AppointmentController::class,'selectPatient'])->name('selectPatient');
        Route::get('/selectDoctor',[AppointmentController::class,'selectDoctor'])->name('selectDoctor');
        Route::post('/add',[AppointmentController::class,'add'])->name('add');
        Route::post('/delete',[AppointmentController::class,'delete'])->name('delete');
        Route::get('/edit/{id}',[AppointmentController::class,'edit'])->name('edit');
        Route::post('/update',[AppointmentController::class,'update'])->name('update');
        Route::get('/pdf/{id}',[AppointmentController::class,'pdf'])->name('pdf');
    });

    //--File--//
    Route::group(['prefix'=>'file','as'=>'file.'],function (){
       Route::get('/',[FileController::class,'index'])->name('index');
       Route::get('/view',[FileController::class,'view'])->name('view');
       Route::post('/store',[FileController::class,'store'])->name('store');
        Route::post('/storeMedia',[FileController::class,'storeMedia'])->name('storeMedia');
       Route::get('/datatable',[FileController::class,'datatable'])->name('datatable');
       Route::get('/datatableMedia',[FileController::class,'datatableMedia'])->name('datatableMedia');
       Route::post('/delete',[FileController::class,'delete'])->name('delete');
       Route::post('/display',[FileController::class,'display'])->name('display');
       Route::get('/mediaView',[FileController::class,'mediaView'])->name('mediaView');
    });

    //--Role--//
    Route::group(['prefix'=>'role','as'=>'role.'],function (){
       Route::get('/',[RoleController::class,'index'])->name('index');
       Route::get('/create',[RoleController::class,'create'])->name('create');

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreDoctorRequest;
use App\Models\Appointment;
use App\Models\DoctorPatient;
use App\Models\Patient;
use Illuminate\Validation\Rule;
use App\Models\Doctor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use PhpParser\Comment\Doc;
use PHPUnit\Framework\MockObject\Stub;
use Yajra\DataTables\Facades\DataTables;
use function GuzzleHttp\Promise\all;
use App\Rules\UpperCaseRule;

class   DoctorController extends Controller
{
    //
    public function index()
    {
        return view('doctors.index');
    }

    public function create()
    {
        return view('doctors.create');
    }

    public function store(StoreDoctorRequest $request)
    {
        $validated = $request->validated();

        $validated = Doctor::create(['first_name' => $request->first_name, 'last_name' => $request->last_name, 'email' => $request->email, 'phone' => $request->phone, 'title' => $request->title, 'address' => $request->address, 'experience' => $request->experience]);
        return response()->json(['success' => true, 'message' => 'Doctor Added Successfully!']);
    }

    public function datatable(Request $request)
    {
        $params = ['keyword' => $request->keyword,];
        $doctor = Doctor::select('*');

        if (isset($params['keyword']) && $params['keyword'] != '') {
            $keyword = $params['keyword'];
            $doctor->where(function ($doctor) use ($keyword) {
                $doctor->orWhere('first_name', 'like', '%' . $keyword . '%');
                $doctor->orWhere('last_name', 'like', '%' . $keyword . '%');
            });
        }

        if (request()->ajax()) {
            return datatables()->of($doctor->orderBy('doctors.id', 'asc')->get())->addColumn('name', function ($data) {
                    return $data->first_name . ' ' . $data->last_name;
                })->addColumn('action', function ($data) {
                    $button = '<div style="width: 422px;"><a href="' . route('doctor.edit', $data->id) . '" class="d-inline-block"> <button type="button" name="edit"   class="edit mr-1 btn btn-primary btn-sm text-right">Edit</button></a>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<a href="#" onclick="delete_doctor(' . $data->id . ')"  class="d-inline-block"><button type="button" name="delete"  class="delete  mr-1  btn btn-danger btn-sm text-right ">Delete</button></a>';
                    $button .= '<a href="#" onclick="appointment(' . $data->id . ')"  class="d-inline-block"><button type="button" name="delete"  class="delete  mr-1  btn btn-danger btn-sm text-right ">Appointment</button></a>';
                    $button .= '<a href="' . route('doctor.patient.index', ['id' => $data->id]) . '" class="d-inline-block"><button type="button" name="delete" class="delete btn btn-dark btn-sm text-right ">Add Patient</button></a></div>';
                    return $button;
                })->rawColumns(['action'])->make(true);
        }

    }

    public function edit(Request $request, $id)
    {
        $doctor = Doctor::findorfail($id);
        return view('doctors.create', ['doctor' => $doctor]);
    }

    public function update(Request $request)
    {

        Validator::make($request->all(), [
            'first_name' => 'required|regex:/^[a-zA-Z]+$/u|min:3|max:10',
            'last_name' => 'required|regex:/^[a-zA-Z]+$/u|min:3|max:10',
            'email' => 'required|email|unique:doctors,email,' . $request->id,
            'phone' => 'required|min:10|unique:doctors,phone,' . $request->id,
            'title' => 'required',
            'address' => 'required',
            'experience' => 'required'
        ])->validate();

        $doctor = Doctor::findorfail($request->id);
        $doctor->first_name = $request->first_name;
        $doctor->last_name = $request->last_name;
        $doctor->email = $request->email;
        $doctor->phone = $request->phone;
        $doctor->title = $request->title;
        $doctor->address = $request->address;
        $doctor->experience = $request->experience;
        $doctor->save();

        return response()->json(['success' => true, 'message' => 'Doctor Updated Successfully!']);

    }

    public function delete(Request $request)
    {

        $doctor = Doctor::find($request->id);
        $doctor->delete();
        return response()->json(['success' => true, 'message' => "Doctor Deleted!"]);
    }

    public function indexDoctorPatient(Request $request)
    {
        $doctor = Doctor::find($request->id);
        return view('doctors.patient.index', compact('doctor'));
    }

    public function addPatient(Request $request)
    {
        $doctor = Doctor::find($request->id);
        return view('doctors.patient.add', compact('doctor'));
    }

    public function patientdatatable(Request $request)
    {
        $patient = Patient::join('doctor_patient', 'doctor_patient.patient_id', '=', 'patients.id')->where('doctor_patient.doctor_id', '=', $request->id)->select('patients.*');

        return Datatables::of($patient->orderBy('doctor_patient.created_at', 'desc'))->addColumn('action', function ($data) {
                $button = '<a href="#"> <button type="button" name="edit" onclick="deletePatient(' . $data->id . ');"   class="edit mr-1 btn btn-primary btn-sm text-right">Delete</button></a>';
                return $button;
            })->rawColumns(['action'])->make(true);

    }

    public function storePatient(Request $request)
    {
        Validator::make($request->all(), ['patient' => 'required|min:1',])->validate();

        foreach ($request->patient as $key) {
            DoctorPatient::create(['patient_id' => $key, 'doctor_id' => $request->doctor_id]);
        }
        return response()->json(['success' => true, 'message' => 'Patient Added Successfully!']);
    }

    public function select(Request $request)
    {
        $doctor = Doctor::findOrFail($request->doctor_id);

        $patient = Patient::leftJoin('doctor_patient', function ($join) use ($doctor) {
            $join->on('doctor_patient.patient_id', '=', 'patients.id');
            $join->where('doctor_patient.doctor_id', '=', $doctor->id);
        })->select('patients.id', 'patients.first_name', 'patients.last_name', 'patients.email')->whereNull('doctor_patient.doctor_id');

        // $patient = Patient::select('*');
        if ($request->has('search')) {
            $keyword = $request->search;
            $patient->where(function ($patient) use ($keyword) {
                $patient->orWhere('patients.first_name', 'like', '%' . $keyword . '%');
                $patient->orWhere('patients.last_name', 'like', '%' . $keyword . '%');
                $patient->orWhere('patients.email', 'like', '%' . $keyword . '%');
            });
        }
        return response()->json($patient->paginate(5, ['*'], 'page', $request->page));
    }

    public function deletePatient(Request $request)
    {
        $patient = DoctorPatient::where('doctor_patient.doctor_id', '=', $request->doctor_id)
            ->where('doctor_patient.patient_id', '=', $request->id)->delete();
        if ($patient) {
            return response()->json(['success' => true, 'message', 'Patient Deleted']);
        } else {
            return response()->json(['success' => false, 'message', 'Patient not found']);
        }
    }

    public function viewAppointment(Request $request)
    {
        $appointment = Appointment::select('*', 'patients.first_name as patient')->leftjoin('patients', 'patients.id', '=', 'appointments.patient_id')->where('appointments.doctor_id', '=', $request->id);

        if (request()->ajax()) {
            return datatables()->of($appointment->orderBy('appointments.id', 'asc')->get())->addColumn('action', function ($data) {

                })->rawColumns(['action'])->make(true);
        }
    }

}

resources/views/doctors/create.blade.php
@extends('layouts.master')
@section('content')

    <div id="layoutSidenav_content">

        <div class="container-fluid px-4">

            <div class="container-fluid px-1 py-5 mx-auto">
                <div class="row d-flex justify-content-center">
                    <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
                        <h3> @if(isset($doctor)) Update @else Add @endif Doctor</h3>

                        <div class="card" id="form-style">
                            <p class="blue-text">Please @if(isset($doctor))Update @else add @endif doctor<br>
                            <form enctype="multipart/form-data" class="form-card" id="create_doctor"
                                  @if(isset($doctor)) action="{{route('doctor.update',['id'=>$doctor->id])}}"
                                  @else action="{{route('doctor.store')}}" @endif method="post">
                                @csrf
                                <div class="row justify-content-between text-left">
                                    <div class="form-group col-sm-6 flex-column d-flex">
                                        <label class="form-control-label px-3">First name</label>
                                        <input type="text" id="first_name" name="first_name"
                                               placeholder="Enter your first name" data-field-name="First-name"
                                               @if(isset($doctor)) value="{{$doctor->first_name}}"
                                               @endif onkeyup="validates(this)" required>
                                        <span class="text-danger error-text"></span>
                                    </div>

                                    <div class="form-group col-sm-6 flex-column d-flex">
                                        <label class="form-control-label px-3">Last name </label>
                                        <input type="text" id="last_name" name="last_name"
                                               placeholder="Enter your last name" data-field-name="Last-name"
                                               @if(isset($doctor)) value="{{$doctor->last_name}}"
                                               @endif onkeyup="validates(this)" required>
                                        <span class="text-danger error-text"></span></div>
                                </div>
                                <div class="row justify-content-between text-left">
                                    <div class="form-group col-sm-6 flex-column d-flex">
                                        <label class="form-control-label px-3">Personal Email</label>
                                        <input type="text" id="email" name="email" placeholder="Enter Email"
                                               @if(isset($doctor)) value="{{$doctor->email}}"
                                               @endif data-field-name="Email" onkeyup="validates(this)" required>
                                        <span class="text-danger error-text"></span>
                                    </div>

                                    <div class="form-group col-sm-6 flex-column d-flex">
                                        <label class="form-control-label px-3">Phone number</label>
                                        <input type="number" id="phone" name="phone" placeholder="Enter Phone Number"
                                               @if(isset($doctor)) value="{{$doctor->phone}}" @endif  data-field-name="Phone-number"
                                               onkeyup="validates(this)" required>
                                        <span class="text-danger error-text"></span>
                                    </div>

                                    <div class="row justify-content-between text-left">
                                        <div class="form-group col-sm-6 flex-column d-flex">
                                            <label class="form-control-label px-3">Dr Title</label>
                                            <input type="text" id="title" name="title" placeholder="Enter title"
                                                   @if(isset($doctor)) value="{{$doctor->title}}" @endif
                                            data-field-name="Title" onkeyup="validates(this)" required >
                                            <span class="text-danger error-text"></span>
                                        </div>
                                        <div class="form-group col-sm-6 flex-column d-flex">
                                            <label class="form-control-label px-3">Adress</label>
                                            <input type="text" id="address" name="address" placeholder="Enter address"
                                                   @if(isset($doctor)) value="{{$doctor->address}}" @endif onkeyup="validates(this)" data-field-name="Address" required>
                                            <span class="text-danger error-text"></span>
                                        </div>
                                    </div>
                                    <div class="row justify-content-between text-left">
                                        <div class="form-group col-sm-6 flex-column d-flex">
                                            <label class="form-control-label px-3">Experience</label>
                                            <input type="text" id="experience" name="experience"
                                                   placeholder="Enter experience"
                                                   @if(isset($doctor)) value="{{$doctor->experience}}" @endif onkeyup="validates(this)" required data-field-name="Experience">
                                            <span class="text-danger error-text"></span>
                                        </div>
                                    </div>
                                    <div class="row justify-content-end">
                                        <div class="form-group col-sm-6">
                                            <button type="button" class="btn-block btn-primary" style="width: 100px;"
                                                    onclick="save('create_doctor');">Save
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('scripts')
    <script>

        function save(form_id) {
            var status = true;
            $("form#" + form_id + " :input").each(function () {
                status = validates(this, status);
            });
            if (status === true) {
                $.ajax({
                    type: 'POST',
                    url: $('#create_doctor').attr('action'),
                    dataType: "json",
                    processData: false,
                    contentType: false,
                    data: new FormData($('#create_doctor')[0]),
                    success: function (response) {
                        if (response.success) {
                            window.location = '{{route('doctor.index')}}';
                        } else {
                            if (response.success == NULL) {
                                printErrorMsg(['Something Went Wrong, please Reload or try Again Later!']);
                            } else {
                                printErrorMsg([response.message]);
                            }
                        }
                    }
                });
            } else {
                return status;
            }
        }

        function validates(object, status) {

            var input = $(object);
            if (input.prop('required') && !input.val()) {
                input.addClass('is-invalid');
                input.addClass('invalid');
                status = false;
                input.siblings('span.error-text').html((input.data('field-name') !== 'undefined') ? input.data('field-name') + ' is required.' : 'is required.');
            } else if (input.val()) {
                var input_id = input.attr('id');
                if (input_id === 'first_name') {
                    status = validate.first_name(input, status);
                } else if (input_id === 'last_name') {
                    status = validate.last_name(input, status);
                } else if (input_id === 'email') {
                    status = validate.email(input, status);
                } else if (input_id === 'phone') {
                    status = validate.phone_number(input, status);
                }else if(input_id === 'title'){
                    status =validate.title(input,status);
                }
                else {
                    input.removeClass('is-invalid');
                    input.siblings('span.error-text').html('');
                }

            } else {
                input.siblings('span.select2-container--default').removeClass('invalid-select');
                input.removeClass('is-invalid');
            }
            return status;
        }

    </script>
@endpush

resources/views/doctors/table.blade.php
{{--    <div id="layoutSidenav_content">--}}

<div class="container-fluid px-4">

    <div class="filters-div">
        <div class="row mt-2 mb-2">
            <div class="col-md-4 col-sm-6 col-12">
                <div class="form-group">
                    <label for="keyword">Search by Keyword</label>
                    <input id="keyword" type="search" class="form-control" placeholder="Enter Keyword" name="">
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-12">
                <label></label>
                <div class="form-group" style="margin-top: 6px;">
                    <button class="btn btn-primary bg-darken-2 text-white" onclick="doctortable.draw();"><i class="ft-search"></i> Search</button>
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table id="doctor_table" class="table border-dark">
            <thead>
            <tr  class="dp-style">
                <th>Id</th>
                <th>Name</th>

                <th>Email</th>
                <th>Phone</th>
                <th>Title</th>
                <th width="200">Address</th>
                <th>Experience</th>
                <th width="300">Actions</th>
            </tr>
            </thead>
        </table>
    </div>
@include('doctors.appointment')
</div>

@push('scripts')
    <script>
        $(document).ready(function () {
            doctortable = $('#doctor_table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url:'{{route('doctor.datatable')}}',
                    data: function (d) {
                        d.keyword = $('#keyword').val();
                    }
                },
                columns: [
                    {
                        data: 'id',
                        name: 'id',
                        sortable:false
                    },
                    {
                        data: 'name',
                        name: 'name',
                        sortable:false
                    },

                    {
                        data: 'email',
                        name: 'email',
                        sortable:false
                    },
                    {
                        data: 'phone',
                        name: 'phone',
                        sortable:false
                    },
                    {
                        data: 'title',
                        name: 'title',
                        sortable:false
                    },
                    {
                        data: 'address',
                        name: 'address',
                        sortable:false
                    },
                    {
                        data: 'experience',
                        name: 'experience',
                        sortable:false
                    }, {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: true
                    }
                ]
            })
        });

        function delete_doctor(id) {

            swal({
                title: "Are you sure?",
                text: "Do you really Want to remove This User?",
                icon: "warning",
                buttons: {
                    No:{
                        text: "No!",
                        value: false,
                    },
                    Yes: {
                        text: "Yes!",
                        value: true,
                    }
                },
            }).then((willDelete) => {
                if (willDelete){
                    $.ajax({
                        type: "POST",
                        url: '{{ route('doctor.delete') }}',
                        data: {
                            '_token': '{{ csrf_token() }}',
                            'id': id,
                        },
                        dataType: 'json',
                        success: function (data) {
                            doctortable.draw();
                        },
                        error: function (data) {
                            console.log(data);
                        }
                    });
                }
            });

        }
    </script>
@endpush