routes/web.php
<?php

use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PdfGenerator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\NurseController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\RoleController;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'verified']], function () {

    Route::get('/index', [DashboardController::class, 'index'])->name('index');
    Route::get('/exportCsv',[DashboardController::class,'exportCsv'])->name('exportCsv');

    Route::group(['prefix' => 'doctor', 'as' => 'doctor.'], function () {
        Route::get('/', [DoctorController::class, 'index'])->name('index');
        Route::get('/create', [DoctorController::class, 'create'])->name('create');
        Route::post('/store', [DoctorController::class, 'store'])->name('store');
        Route::get('/datatable', [DoctorController::class, 'datatable'])->name('datatable');
        Route::get('/edit/{id}', [DoctorController::class, 'edit'])->name('edit');
        Route::post('/update', [DoctorController::class, 'update'])->name('update');
        Route::post('/delete', [DoctorController::class, 'delete'])->name('delete');
        Route::get('/viewAppointment',[DoctorController::class,'viewAppointment'])->name('viewAppointment');

        //---Doctor Patient Routes---//
        Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
            Route::get('/', [DoctorController::class, 'indexDoctorPatient'])->name('index');
            Route::get('/select', [DoctorController::class, 'select'])->name('select');
            Route::get('/add/{id}', [DoctorController::class, 'addPatient'])->name('addPatient');
            Route::get('/patientdatatable', [DoctorController::class, 'patientdatatable'])->name('patientdatatable');
            Route::post('/store', [DoctorController::class, 'storePatient'])->name('storePatient');
            Route::post('/delete', [DoctorController::class, 'deletePatient'])->name('deletePatient');

        });
    });

    //--Nurses Route--//
    Route::group(['prefix' => 'nurse', 'as' => 'nurse.'], function () {
        Route::get('/', [NurseController::class, 'index'])->name('index');
        Route::get('/create', [NurseController::class, 'create'])->name('create');
        Route::post('/store', [NurseController::class, 'store'])->name('store');
        Route::get('/datatable', [NurseController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [NurseController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [NurseController::class, 'edit'])->name('edit');
        Route::post('/update', [NurseController::class, 'update'])->name('update');
        Route::get('/selectDepartment', [NurseController::class, 'selectDepartment'])->name('selectDepartment');
    });

    //--Staff Route--//
    Route::group(['prefix' => 'staff', 'as' => 'staff.'], function () {
        Route::get('/', [StaffController::class, 'index'])->name('index');
        Route::get('/create', [StaffController::class, 'create'])->name('create');
        Route::post('/store', [StaffController::class, 'store'])->name('store');
        Route::get('/datatable', [StaffController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [StaffController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [StaffController::class, 'edit'])->name('edit');
        Route::post('/update', [StaffController::class, 'update'])->name('update');
    });

    //--Department--//
    Route::group(['prefix' => 'department', 'as' => 'department.'], function () {
        Route::get('/', [DepartmentController::class, 'index'])->name('index');
        Route::get('/create', [DepartmentController::class, 'create'])->name('create');
        Route::post('/store', [DepartmentController::class, 'store'])->name('store');
        Route::get('/datatable', [DepartmentController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [DepartmentController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [DepartmentController::class, 'edit'])->name('edit');
        Route::post('/update', [DepartmentController::class, 'update'])->name('update');
    });

    //--Patient--//
    Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
        Route::get('/', [PatientController::class, 'index'])->name('index');
        Route::get('/create', [PatientController::class, 'create'])->name('create');
        Route::post('/store', [PatientController::class, 'store'])->name('store');
        Route::get('/datatable', [PatientController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [PatientController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [PatientController::class, 'edit'])->name('edit');
        Route::post('/update', [PatientController::class, 'update'])->name('update');
        Route::get('/viewAppointment',[PatientController::class,'viewAppointment'])->name('viewAppointment');
    });

    //---User Routes---//
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/add',[UserController::class,'add'])->name('add');
        Route::get('/view',[UserController::class,'view'])->name('view');
        Route::post('/create',[UserController::class,'create'])->name('create');
        Route::get('/edit/{id}', [UserController::class, 'index'])->name('edit');
        Route::post('/update', [UserController::class, 'update'])->name('update');
        Route::get('/datatable',[UserController::class,'usersList'])->name('datatable');
        Route::post('/delete',[UserController::class,'delete'])->name('delete');
    });

//---Room Routes---//
    Route::group(['prefix' => 'room', 'as' => 'room.'], function () {
        Route::get('/', [RoomController::class, 'index'])->name('index');
        Route::get('/create', [RoomController::class, 'create'])->name('create');
        Route::post('/store', [RoomController::class, 'store'])->name('store');
        Route::get('/datatable',[RoomController::class,'datatable'])->name('datatable');
        Route::post('/delete',[RoomController::class,'delete'])->name('delete');
        Route::get('/edit/{id}',[RoomController::class,'edit'])->name('edit');
        Route::post('update',[RoomController::class,'update'])->name('update');

        Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
            Route::get('/', [RoomController::class, 'indexpatient'])->name('index');
            Route::get('/create',[RoomController::class,'createPatient'])->name('create');
            Route::post('/store',[RoomController::class,'storePatient'])->name('store');
            Route::get('/select',[RoomController::class,'select'])->name('select');
            Route::get('/patientDatatable',[RoomController::class,'patientDatatable'])->name('patientDatatable');
            Route::post('/delete',[RoomController::class,'deletePatient'])->name('delete');
        });

    });

    //---Appointment Routes---//
    Route::group(['prefix' => 'appointment', 'as' => 'appointment.'], function () {
        Route::get('/', [AppointmentController::class, 'index'])->name('index');
        Route::get('/create',[AppointmentController::class,'create'])->name('create');
        Route::get('/datatable',[AppointmentController::class,'datatable'])->name('datatable');
        Route::get('/selectPatient',[AppointmentController::class,'selectPatient'])->name('selectPatient');
        Route::get('/selectDoctor',[AppointmentController::class,'selectDoctor'])->name('selectDoctor');
        Route::post('/add',[AppointmentController::class,'add'])->name('add');
        Route::post('/delete',[AppointmentController::class,'delete'])->name('delete');
        Route::get('/edit/{id}',[AppointmentController::class,'edit'])->name('edit');
        Route::post('/update',[AppointmentController::class,'update'])->name('update');
        Route::get('/pdf/{id}',[AppointmentController::class,'pdf'])->name('pdf');
    });

    //--File--//
    Route::group(['prefix'=>'file','as'=>'file.'],function (){
       Route::get('/',[FileController::class,'index'])->name('index');
       Route::get('/view',[FileController::class,'view'])->name('view');
       Route::post('/store',[FileController::class,'store'])->name('store');
        Route::post('/storeMedia',[FileController::class,'storeMedia'])->name('storeMedia');
       Route::get('/datatable',[FileController::class,'datatable'])->name('datatable');
       Route::get('/datatableMedia',[FileController::class,'datatableMedia'])->name('datatableMedia');
       Route::post('/delete',[FileController::class,'delete'])->name('delete');
       Route::post('/display',[FileController::class,'display'])->name('display');
       Route::get('/mediaView',[FileController::class,'mediaView'])->name('mediaView');
    });

    //--Role--//
    Route::group(['prefix'=>'role','as'=>'role.'],function (){
       Route::get('/',[RoleController::class,'index'])->name('index');
       Route::get('/create',[RoleController::class,'create'])->name('create');

resources/views/nurses/create.blade.php
@extends('layouts.master')
@section('content')

    <div id="layoutSidenav_content">

        <div class="container-fluid px-4">

            <div class="container-fluid px-1 py-5 mx-auto">
                <div class="row d-flex justify-content-center">
                    <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
                        <h3>@if(isset($nurse)) Update @else Add @endif Nurse</h3>
                        <div class="card">
                            <p class="blue-text">Please @if(isset($nurse)) Update @else  add @endif nurse<br>
                            <form enctype="multipart/form-data" class="form-card" id="create_nurse"
                               @if(isset($nurse)) action="{{route('nurse.update',['id'=>$nurse->id])}}"
                                  @else action="{{route('nurse.store')}}" @endif method="post">
                                @csrf
                                <div class="row justify-content-between text-left">
                                    <div class="form-group col-sm-6 flex-column d-flex">
                                        <label class="form-control-label px-3">First name</label>
                                        <input type="text" id="first_name" name="first_name"
                                               placeholder="Enter your first name" data-field-name="First-name" @if(isset($nurse)) value="{{$nurse->first_name}}" @endif
                                                  onkeyup="validation(this)" required>
                                        <span class="text-danger error-text"></span>
                                    </div>

                                    <div class="form-group col-sm-6 flex-column d-flex">
                                        <label class="form-control-label px-3">Last name </label>
                                        <input type="text" id="last_name" name="last_name"
                                               placeholder="Enter your last name" data-field-name="Last-name" @if(isset($nurse)) value="{{$nurse->last_name}}" @endif
                                              onkeyup="validation(this)" required>
                                        <span class="text-danger error-text"></span></div>
                                </div>
                                <div class="row justify-content-between text-left">
                                    <div class="form-group col-sm-6 flex-column d-flex">
                                        <label class="form-control-label px-3">Personal Email</label>
                                        <input type="text" id="email" name="email" placeholder="Enter Email"
                                                @if(isset($nurse)) value="{{$nurse->email}}" @endif
                                                data-field-name="Email" onkeyup="validation(this)"   required>
                                        <span class="text-danger error-text"></span>
                                    </div>

                                    <div class="form-group col-sm-6 flex-column d-flex">
                                        <label class="form-control-label px-3">Phone number</label>
                                        <input type="number" id="phone" name="phone" placeholder="Enter Phone Number"
                                               @if(isset($nurse)) value="{{$nurse->phone}}" @endif
                                               data-field-name="Phone-number" onkeyup="validation(this)" required>
                                        <span class="text-danger error-text"></span>
                                    </div>

                                    <div class="row justify-content-between text-left">
                                        <div class="form-group col-sm-6 flex-column d-flex">
                                            <label class="form-control-label px-3">Position</label>
                                            <input type="position" id="position" name="position" placeholder="Enter position"
                                                @if(isset($nurse)) value="{{$nurse->position}}" @endif
                                                   data-field-name="Position" onkeyup="validation(this)"  required >
                                            <span class="text-danger error-text"></span>
                                        </div>
                                        <div class="form-group col-sm-6 flex-column d-flex">
                                            <label class="form-control-label px-3">Joined At</label>
                                            <input type="date" id="joined_at" name="joined_at"   @if(isset($nurse))  value="{{\Carbon\Carbon::parse($nurse->joined_at)->format('Y-m-d')}}" @endif
                                                  data-field-name="Date" required>
                                            <span class="text-danger error-text"></span>
                                        </div>
                                    </div>
                                    <div class="row justify-content-between text-left">
                                        <div class="form-group col-sm-6 flex-column d-flex">
                                            <div class="form-group">
                                                <label for="department">Add Department</label>
                                                <select id="department" data-field-name="Department"
                                                        class="form-control select2-reset"
                                                        name="department"  required>

                                                    <option></option>
                                                    @if(isset($nurse))
                                                        @if(!empty($nurse->department))
                                                            <option value="{{$nurse->department->id}}" selected>{{$nurse->department->name}}</option>
                                                        @endif
                                                    @endif
                                                </select>
                                                <span class="text-danger error-text"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row justify-content-end">
                                        <div class="form-group col-sm-6">
                                            <button type="button" class="btn-block btn-primary" style="width: 100px;"
                                                    onclick="save('create_nurse');">Save
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('scripts')
    <script>
    function save(form_id)
    {
        var status = true;
        $("form#" + form_id + " :input").each(function (){
            status = validation(this,status);
        });
        if(status === true) {
            $.ajax({
                type: 'POST',
                url: $('#create_nurse').attr('action'),
                dataType: "json",
                processData: false,
                contentType: false,
                data: new FormData($('#create_nurse')[0]),
                success: function (response) {
                    if (response.success) {
                        console.log(response.success);
                        window.location = '{{route('nurse.index')}}';
                    } else {
                        console.log(response.error);
                        if (response.success == NULL) {
                            printErrorMsg(['Something Went Wrong, please Reload or try Again Later!']);
                        } else {
                            printErrorMsg([response.message]);
                        }
                    }
                }
            });
        }else{
            return status;
        }
    }

    function validation(object,status)
    {
        var input = $(object);
        if(input.prop('required') && !input.val())
        {
            input.addClass('is-invalid');
            input.addClass('invalid');
            status = false;
            input.siblings('span.error-text').html((input.data('field-name') !== 'undefined') ? input.data('field-name') + ' is required.' : 'is required.');
        }else if(input.val()){
            var input_id = input.attr('id');
            if(input_id === 'first_name')
            {
                status = validate.first_name(input,status);
            }else if(input_id === 'last_name')
            {
                status = validate.last_name(input, status);
            }else if(input_id === 'email')
            {
                status = validate.email(input,status);
            }else if(input_id === 'phone')
            {
                status = validate.phone_number(input,status);
            }
            else if(input_id === 'position')
            {
                status = validate.title(input,status);
            }
            else {
                input.removeClass('is-invalid');
                input.siblings('span.error-text').html('');
            }
        }
        else{
            input.siblings('span.select2-container--default').removeClass('invalid-select');
            input.removeClass('is-invalid');
        }
        return status;
    }

    $(document).ready(function () {
        $('#department').select2({
            placeholder: 'Select Department',
            ajax: {
                url: '{{route('nurse.selectDepartment')}}',
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                        search: params.term,
                        page: params.page || 1
                    };
                },
                processResults: function (data) {
                    return {
                        results: $.map(data.data, function (item) {
                            return {
                                id: item.id,
                                text: item.name
                            }
                        }),
                        pagination: {
                            more: (data.current_page < data.last_page)
                        }
                    };
                },
                cache: true
            }

        });
    });

    </script>
@endpush

resources/views/nurses/index.blade.php
@extends('layouts.master')
@section('content')

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <a href="{{route('nurse.create')}}"> <button class="float-right">Add Nurse</button></a>
                @include('nurses.table')
            </div>
        </main>

    </div>

@endsection

@push('scripts')

@endpush

resources/views/nurses/table.blade.php
<div class="container-fluid px-4">

    <div class="filters-div">
        <div class="row mt-2 mb-2">
            <div class="col-md-4 col-sm-6 col-12">
                <div class="form-group">
                    <label for="keyword">Search by Keyword</label>
                    <input id="keyword" type="search" class="form-control" placeholder="Enter Keyword" name="">
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-12">
                <label></label>
                <div class="form-group" style="margin-top: 6px;">
                    <button class="btn btn-primary bg-darken-2 text-white" onclick="nursetable.draw();"><i class="ft-search"></i> Search</button>
                </div>
            </div>
        </div>
    </div>

    <div>
        <table id="nurse_table" class="table table-responsive border-dark">
            <thead>
            <tr class="dp-style">
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Position</th>
                <th>Joined At</th>
                <th>Department</th>
                <th width="200px">Actions</th>
            </tr>
            </thead>
        </table>
    </div>

</div>
@push('scripts')
    <script>
        $(document).ready(function () {
            nursetable = $('#nurse_table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url:'{{route('nurse.datatable')}}',
                    data: function (d){
                        d.keyword = $('#keyword').val();
                    }
                },
                columns: [
                    {
                        data: 'id',
                        name: 'id',
                        sortable: false
                    },
                    {
                        data: 'name',
                        name: 'name',
                        sortable: false
                    },

                    {
                        data: 'email',
                        name: 'email',
                        sortable: false
                    },
                    {
                        data: 'phone',
                        name: 'phone',
                        sortable: false
                    },
                    {
                        data: 'position',
                        name: 'position',
                        sortable: false
                    },
                    {
                        data: 'joined_at',
                        name: 'joined_at',
                        sortable: false
                    },
                    {
                        data: 'department',
                        name: 'department',
                        sortable: false
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable:false,
                        searchable:true
                    },
                ]
            })
        });

        function deleteNurse(id)
        {
            swal({
                title: "Are you sure?",
                text: "Do you really Want to remove This User?",
                icon: "warning",
                buttons: {
                    No:{
                        text: "No!",
                        value: false,
                    },
                    Yes: {
                        text: "Yes!",
                        value: true,
                    }
                },
            }).then((willDelete) => {
                if (willDelete){
                    $.ajax({
                        type: "POST",
                        url: '{{ route('nurse.delete') }}',
                        data: {
                            '_token': '{{ csrf_token() }}',
                            'id': id,
                        },
                        dataType: 'json',
                        success: function (data) {
                            nursetable.draw();
                        },
                        error: function (data) {
                            console.log(data);
                        }
                    });
                }
            });

        }
    </script>
@endpush