routes/web.php
<?php

use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PdfGenerator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\NurseController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\RoleController;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'verified']], function () {

    Route::get('/index', [DashboardController::class, 'index'])->name('index');
    Route::get('/exportCsv',[DashboardController::class,'exportCsv'])->name('exportCsv');

    Route::group(['prefix' => 'doctor', 'as' => 'doctor.'], function () {
        Route::get('/', [DoctorController::class, 'index'])->name('index');
        Route::get('/create', [DoctorController::class, 'create'])->name('create');
        Route::post('/store', [DoctorController::class, 'store'])->name('store');
        Route::get('/datatable', [DoctorController::class, 'datatable'])->name('datatable');
        Route::get('/edit/{id}', [DoctorController::class, 'edit'])->name('edit');
        Route::post('/update', [DoctorController::class, 'update'])->name('update');
        Route::post('/delete', [DoctorController::class, 'delete'])->name('delete');
        Route::get('/viewAppointment',[DoctorController::class,'viewAppointment'])->name('viewAppointment');

        //---Doctor Patient Routes---//
        Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
            Route::get('/', [DoctorController::class, 'indexDoctorPatient'])->name('index');
            Route::get('/select', [DoctorController::class, 'select'])->name('select');
            Route::get('/add/{id}', [DoctorController::class, 'addPatient'])->name('addPatient');
            Route::get('/patientdatatable', [DoctorController::class, 'patientdatatable'])->name('patientdatatable');
            Route::post('/store', [DoctorController::class, 'storePatient'])->name('storePatient');
            Route::post('/delete', [DoctorController::class, 'deletePatient'])->name('deletePatient');

        });
    });

    //--Nurses Route--//
    Route::group(['prefix' => 'nurse', 'as' => 'nurse.'], function () {
        Route::get('/', [NurseController::class, 'index'])->name('index');
        Route::get('/create', [NurseController::class, 'create'])->name('create');
        Route::post('/store', [NurseController::class, 'store'])->name('store');
        Route::get('/datatable', [NurseController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [NurseController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [NurseController::class, 'edit'])->name('edit');
        Route::post('/update', [NurseController::class, 'update'])->name('update');
        Route::get('/selectDepartment', [NurseController::class, 'selectDepartment'])->name('selectDepartment');
    });

    //--Staff Route--//
    Route::group(['prefix' => 'staff', 'as' => 'staff.'], function () {
        Route::get('/', [StaffController::class, 'index'])->name('index');
        Route::get('/create', [StaffController::class, 'create'])->name('create');
        Route::post('/store', [StaffController::class, 'store'])->name('store');
        Route::get('/datatable', [StaffController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [StaffController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [StaffController::class, 'edit'])->name('edit');
        Route::post('/update', [StaffController::class, 'update'])->name('update');
    });

    //--Department--//
    Route::group(['prefix' => 'department', 'as' => 'department.'], function () {
        Route::get('/', [DepartmentController::class, 'index'])->name('index');
        Route::get('/create', [DepartmentController::class, 'create'])->name('create');
        Route::post('/store', [DepartmentController::class, 'store'])->name('store');
        Route::get('/datatable', [DepartmentController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [DepartmentController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [DepartmentController::class, 'edit'])->name('edit');
        Route::post('/update', [DepartmentController::class, 'update'])->name('update');
    });

    //--Patient--//
    Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
        Route::get('/', [PatientController::class, 'index'])->name('index');
        Route::get('/create', [PatientController::class, 'create'])->name('create');
        Route::post('/store', [PatientController::class, 'store'])->name('store');
        Route::get('/datatable', [PatientController::class, 'datatable'])->name('datatable');
        Route::post('/delete', [PatientController::class, 'delete'])->name('delete');
        Route::get('/edit/{id}', [PatientController::class, 'edit'])->name('edit');
        Route::post('/update', [PatientController::class, 'update'])->name('update');
        Route::get('/viewAppointment',[PatientController::class,'viewAppointment'])->name('viewAppointment');
    });

    //---User Routes---//
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/add',[UserController::class,'add'])->name('add');
        Route::get('/view',[UserController::class,'view'])->name('view');
        Route::post('/create',[UserController::class,'create'])->name('create');
        Route::get('/edit/{id}', [UserController::class, 'index'])->name('edit');
        Route::post('/update', [UserController::class, 'update'])->name('update');
        Route::get('/datatable',[UserController::class,'usersList'])->name('datatable');
        Route::post('/delete',[UserController::class,'delete'])->name('delete');
    });

//---Room Routes---//
    Route::group(['prefix' => 'room', 'as' => 'room.'], function () {
        Route::get('/', [RoomController::class, 'index'])->name('index');
        Route::get('/create', [RoomController::class, 'create'])->name('create');
        Route::post('/store', [RoomController::class, 'store'])->name('store');
        Route::get('/datatable',[RoomController::class,'datatable'])->name('datatable');
        Route::post('/delete',[RoomController::class,'delete'])->name('delete');
        Route::get('/edit/{id}',[RoomController::class,'edit'])->name('edit');
        Route::post('update',[RoomController::class,'update'])->name('update');

        Route::group(['prefix' => 'patient', 'as' => 'patient.'], function () {
            Route::get('/', [RoomController::class, 'indexpatient'])->name('index');
            Route::get('/create',[RoomController::class,'createPatient'])->name('create');
            Route::post('/store',[RoomController::class,'storePatient'])->name('store');
            Route::get('/select',[RoomController::class,'select'])->name('select');
            Route::get('/patientDatatable',[RoomController::class,'patientDatatable'])->name('patientDatatable');
            Route::post('/delete',[RoomController::class,'deletePatient'])->name('delete');
        });

    });

    //---Appointment Routes---//
    Route::group(['prefix' => 'appointment', 'as' => 'appointment.'], function () {
        Route::get('/', [AppointmentController::class, 'index'])->name('index');
        Route::get('/create',[AppointmentController::class,'create'])->name('create');
        Route::get('/datatable',[AppointmentController::class,'datatable'])->name('datatable');
        Route::get('/selectPatient',[AppointmentController::class,'selectPatient'])->name('selectPatient');
        Route::get('/selectDoctor',[AppointmentController::class,'selectDoctor'])->name('selectDoctor');
        Route::post('/add',[AppointmentController::class,'add'])->name('add');
        Route::post('/delete',[AppointmentController::class,'delete'])->name('delete');
        Route::get('/edit/{id}',[AppointmentController::class,'edit'])->name('edit');
        Route::post('/update',[AppointmentController::class,'update'])->name('update');
        Route::get('/pdf/{id}',[AppointmentController::class,'pdf'])->name('pdf');
    });

    //--File--//
    Route::group(['prefix'=>'file','as'=>'file.'],function (){
       Route::get('/',[FileController::class,'index'])->name('index');
       Route::get('/view',[FileController::class,'view'])->name('view');
       Route::post('/store',[FileController::class,'store'])->name('store');
        Route::post('/storeMedia',[FileController::class,'storeMedia'])->name('storeMedia');
       Route::get('/datatable',[FileController::class,'datatable'])->name('datatable');
       Route::get('/datatableMedia',[FileController::class,'datatableMedia'])->name('datatableMedia');
       Route::post('/delete',[FileController::class,'delete'])->name('delete');
       Route::post('/display',[FileController::class,'display'])->name('display');
       Route::get('/mediaView',[FileController::class,'mediaView'])->name('mediaView');
    });

    //--Role--//
    Route::group(['prefix'=>'role','as'=>'role.'],function (){
       Route::get('/',[RoleController::class,'index'])->name('index');
       Route::get('/create',[RoleController::class,'create'])->name('create');

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    use HasFactory;

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'phone',
        'age',
        'weight',
        'address',
        'disease',
        'gender'
    ];

    public function doctorPatient()
    {
        return $this->hasMany(DoctorPatient::class);
    }
    public function doctors()
    {
        return $this->belongsToMany(Doctor::class,'doctor_patient','patient_id','doctor_id');
    }

    public function roomPatient()
    {
        return $this->hasMany(RoomPatient::class);
    }
    public function rooms()
    {
        return $this->belongsToMany(Room::class,'room_patient','patient_id','room_id');
    }

}

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use HasFactory;
    protected $fillable=[
      'floor_no',
        'room_no',
        'total_bed'
    ];
    public function roomPatient()
    {
        return $this->hasMany(RoomPatient::class);
    }

    public function patients()
    {
        return $this->belongsToMany(Patient::class, 'room_patient', 'room_id', 'patient_id');
    }
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;
use App\Models\Appointment;
use App\Models\Patient;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class PatientController extends Controller
{
    //
    public function index()
    {
        return view('patient.index');
    }
    public function create()
    {
        return view('patient.create');
    }
    public function store(Request $request)
    {
        Validator::make($request->all(),[
            'first_name'=>'required|regex:/^[a-zA-Z]+$/u|min:3|max:10',
            'last_name'=>'required|regex:/^[a-zA-Z]+$/u|min:3|max:10',
            'email'=>'required|unique:patients|email|',
            'phone'=>'required|min:10',
            'age'=>'required',
            'weight'=>'required',
            'address'=>'required',
            'disease'=>'required',
            'gender'=>'required',
        ]);
        Patient::create([
            'first_name'=>$request->first_name,
            'last_name'=>$request->last_name,
            'email'=>$request->email,
            'phone'=>$request->phone,
            'age'=>$request->age,
            'weight'=>$request->weight,
            'address'=>$request->address,
            'disease'=>$request->disease,
            'gender'=>$request->gender,
        ]);
        return response()->json(['success'=>true,'message'=>'Patient Added Successfully']);
    }
    public function datatable(Request $request)
    {
        $params = [
          'keyword'=>$request->keyword,
        ];
        $patient = Patient::select('*');

        if(isset($params['keyword']) && $params['keyword'] != ''){
            $keyword = $params['keyword'];
            $patient->where(function ($patient) use ($keyword){
               $patient->orWhere('first_name','like','%'.$keyword.'%');
               $patient->orWhere('last_name','like','%'.$keyword,'%');
            });
        }
        if(request()->ajax())
        {
            return datatables()->of($patient->orderBy('patients.id','asc')->get())
                ->addColumn('name',function ($data){
                    return $data->first_name. ' '.$data->last_name;
                })
                ->addColumn('action', function($data){
                    $button = '<div style="width: 330px;"><a href="'.route('patient.edit',['id'=>$data->id]).'"> <button type="button" name="edit"   class="edit mr-1 btn btn-primary btn-sm text-right">Edit</button></a>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<a href="#" onclick="deletePatient('.$data->id.')"> <button type="button" name="delete"  class="delete mr-1 btn btn-danger btn-sm text-right">Delete</button></a>';
                    $button .= '<a href="#" onclick="viewAppointment('.$data->id.')"> <button  type="button" name="manage"  class="delete btn btn-secondary btn-sm ">View Appointment</button></a></div>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }
    public function delete(Request $request)
    {
        $patient = Patient::findorfail($request->id);
        $patient->delete();
        return response()->json(['success'=>true,'message'=>'Patient deleted Successfully']);
    }
    public function edit(Request $request,$id)
    {
        $patient = Patient::findorfail($id);
        return view('patient.create',['patient'=>$patient]);
    }
    public function update(Request $request)
    {
        Validator::make($request->all(),[
            'first_name'=>'required|regex:/^[a-zA-Z]+$/u|min:3|max:10',
            'last_name'=>'required|regex:/^[a-zA-Z]+$/u|min:3|max:10',
            'email'=>'required|unique:patients|email|',
            'phone'=>'required|min:10',
            'age'=>'required',
            'weight'=>'required',
            'address'=>'required',
            'disease'=>'required',
            'gender'=>'required',
        ]);
        $patient = Patient::findorfail($request->id);
        $patient->first_name = $request->first_name;
        $patient->last_name = $request->last_name;
        $patient->email = $request->email;
        $patient->phone = $request->phone;
        $patient->age = $request->age;
        $patient->weight = $request->weight;
        $patient->address = $request->address;
        $patient->disease = $request->disease;
        $patient->gender = $request->gender;
        $patient->save();

        return response()->json(['success'=>true,'message'=>'Patient Updated Successfully']);
    }
    public function viewAppointment(Request $request)
    {
        $appointment = Appointment::select('*','doctors.first_name as doctor')
            ->leftjoin('doctors','doctors.id','=','appointments.doctor_id')
            ->where('appointments.patient_id','=',$request->id);

        if(request()->ajax())
        {
            return datatables()->of($appointment->orderBy('appointments.id','asc')->get())
                ->addColumn('action', function($data){
                    $button = '<a href="#"> <button type="button" name="edit"   class="edit mr-1 btn btn-primary btn-sm text-right">Action</button></a>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }
}

resources/views/room/patient/add.blade.php
<div class="modal" id="add-room-Modal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-gradient-x-blue bg-darken-2">
                <h4 id="add-edit-department-modal-heading" class="modal-title">Add Patients to Rooms</h4>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                @include('partials.js-validation')
                <form class="form" method="post" id="save-patient-form"
                      action="{{route('room.patient.store')}}">
                    {{csrf_field()}}
                    <div class="form-body">
                        <input type="hidden" value="@if(isset($room)){{$room->id}}@endif" name="room_id">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="patient">Patients</label>
                                    <select id="patient" data-field-name="Patients"
                                            class="form-control select2-reset"
                                            name="patient[]" multiple="multiple" required style="width: 100%;">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" style="float: right;" id="save-person-form-btn"
                            data-loading="<i class='la la-spinner la-spin'></i> Saving..."
                            onclick="storePatient('save-patient-form');"
                            class="btn btn-success">
                        <i class="ft ft-check-square"></i> Save
                    </button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>


@push('scripts')
    <script>
        $(document).ready(function () {
            $('#patient').select2({
                placeholder: 'Select Patient',
                dropdownParent: $('#add-room-Modal'),
                ajax: {
                    url: '{{route('room.patient.select')}}',
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            room_id: '@if(isset($room)){{$room->id}}@endif',
                            search: params.term,
                            page: params.page || 1
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: $.map(data.data, function (item) {
                                return {
                                    id: item.id,
                                    text: item.first_name + ' ' + item.last_name + ' - ' + item.email
                                }
                            }),
                            pagination: {
                                more: (data.current_page < data.last_page)
                            }
                        };
                    },
                    cache: true
                }
            });
        });

        function addRoomPatientModal() {
            $('#add-room-Modal').modal('show');
        }

        function storePatient(form_id) {
            $.ajax({
                type: 'POST',
                url: $('#save-patient-form').attr('action'),
                dataType: "json",
                processData: false,
                contentType: false,
                data: new FormData($('#save-patient-form')[0]),
                success: function (response) {
                    if (response.success) {
                        $('#add-room-Modal').modal('hide');
                        patienttable.draw();
                    } else {
                        if (response.success == NULL) {
                            printErrorMsg(['Something Went Wrong, please Reload or try Again Later!']);
                        } else {
                            printErrorMsg([response.message]);
                        }
                    }
                }
            });
        }
    </script>
@endpush

resources/views/room/patient/index.blade.php
@extends('layouts.master')
@section('content')
    @include('room.patient.add')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <button class="float-right" onclick="addRoomPatientModal();">Adding Room to patient </button>
                @include('room.patient.table')
            </div>
        </main>

    </div>

@endsection

@push('scripts')
    <script>

    </script>
@endpush

resources/views/room/patient/table.blade.php
<div class="container-fluid px-4">

    Hi !!! this is datatable for Manage Room of patient
    <div class="table-responsive">
        <table id="patients_table" class="table border-dark">
            <thead>
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Age</th>
                <th>Weight</th>
                <th>Address</th>
                <th>Disease</th>
                <th>Gender</th>
                <th width="100">Delete</th>
            </tr>
            </thead>
        </table>
    </div>

</div>
@push('scripts')
    <script>
        $(document).ready(function () {

        });

        patienttable = $('#patients_table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{route('room.patient.patientDatatable')}}",
                data: function (d) {
                    d.id = {{$room->id}};
                },
                error: function (xhr, error, thrown) {
                    console.log(error);
                },
            },
            columns: [
                {
                    data: 'id',
                    name: 'id',
                    sortable: false
                },
                {
                    data: 'first_name',
                    name: 'first_name',
                    sortable: false
                },
                {
                    data: 'last_name',
                    name: 'last_name',
                    sortable: false
                },
                {
                    data: 'email',
                    name: 'email',
                    sortable: false
                },
                {
                    data: 'phone',
                    name: 'phone',
                    sortable: false
                },
                {
                    data: 'age',
                    name: 'age',
                    sortable: false
                },
                {
                    data: 'weight',
                    name: 'weight',
                    sortable: false
                },
                {
                    data: 'address',
                    name: 'address',
                    sortable: false
                },
                {
                    data: 'disease',
                    name: 'disease',
                    sortable: false
                },
                {
                    data: 'gender',
                    name: 'gender',
                    sortable: false
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable:false,
                    searchable:true
                },
            ]
        });

        function deletePatient(id) {
            swal({
                title: "Are you sure?",
                text: "Do you really Want to remove This Patient?",
                icon: "warning",
                buttons: {
                    No: {
                        text: "No!",
                        value: false,
                    },
                    Yes: {
                        text: "Yes!",
                        value: true,
                    }
                },
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: "POST",
                        url: '{{ route('room.patient.delete') }}',
                        data: {
                            '_token': '{{ csrf_token() }}',
                            'id': id,
                            'room_id':'@if(isset($room)){{$room->id}}@endif'
                        },
                        dataType: 'json',
                        success: function (data) {
                            patienttable.draw();
                        },
                        error: function (data) {
                            console.log(data);
                        }
                    });
                }
            });
        }

    </script>
@endpush